### ISSUE TITLE
[Question]: ed25519 vs secp256k1

### ISSUE THREAD

**Issue by JhonnyJason** [pedrouid/eccrypto-js#11]
Hallo!
First of all, awesome port! Thank you! :D

For my current system I'm using ed25519 keys everywhere.
- would it easily be possible to add ed25519 into this project?
- what is your take on secp256k1 compared to ed25519

As far as I know there is a vulnerability on ed25519 keys if the adversary has control over the hardware while the key is generated.

As for secp256k1:
https://crypto.stackexchange.com/questions/68269/does-secp256k1-have-any-known-weaknesses 

So far it seems for diffie-hellman is not a "good idea" with secp256k1.
Which would be kind of my primary usecase.^^

Cheers!

**Comment by pedrouid** [comment]
Thanks! 🙌 

Honestly I would go with ed25519 for anything that isn't related to cryptocurrency directly. 

However this library is focused on secp256k1 for cryptocurrency use-cases and it's true that DH for secp256k1 is not a great idea but it provides a good backwards-compatibility for the cryptocurrency wallets for example.

If you would like to use ed25519 there are fortunately much better libraries than this one since it's more broadly used than secp256k1. My recommendation would be to use [dchest/tweetnacl-js](https://github.com/dchest/tweetnacl-js) instead

**Comment by JhonnyJason** [comment]
Cool, thank you very much for the recommendation :+1:
